/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_xingye_netzoo_zooapplication_utils_AddFuncUtils.h"
/*
 * Class:     com_xingye_netzoo_zooapplication_utils_AddFuncUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xingye_netzoo_zooapplication_utils_AddFuncUtils_add
  (JNIEnv *env, jclass jclass1, jint a, jint b)
{
    return (a+b);
}
