/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xingye_netzoo_zooapplication_utils_AddFuncUtils */

#ifndef _Included_com_xingye_netzoo_zooapplication_utils_AddFuncUtils
#define _Included_com_xingye_netzoo_zooapplication_utils_AddFuncUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xingye_netzoo_zooapplication_utils_AddFuncUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xingye_netzoo_zooapplication_utils_AddFuncUtils_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
